-- CoMind One‑Shot v2 - MASTER.sql
\i '00_roles_rls.sql'
\i '01_extensions.sql'
\i '02_schema_core.sql'
\i '03_schema_graph_rag.sql'
\i '04_schema_agents_tasks.sql'
\i '05_schema_decision_conflict.sql'
\i '06_schema_manual_marketing_ticketing_glossary.sql'
\i '07_schema_security_compliance_auth.sql'
\i '08_indexes_constraints.sql'
\i '09_functions_triggers.sql'
\i '10_rls_policies.sql'
\i '11_seed.sql'
\i '12_enterprise_checklist.sql'
\i '13_research_refs.sql'
